// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Meu perfil",
  description: "Retorna o perfil e o papel (aluno, instrutor, investidor, admin) do usu\xE1rio autenticado.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error } = await supabase.from("profiles").select("id, full_name, city, neighborhood, phone, status, verification_status, balance, balance_pending, total_withdrawn, created_at").eq("id", userId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", userId);
    const result = { ...profile, roles: (roles ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { profile: result }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.1.13";
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "Minhas aulas agendadas",
  description: "Lista as aulas do usu\xE1rio autenticado (como aluno ou instrutor), com data, hor\xE1rio, status e valor. Permite filtrar por status.",
  inputSchema: {
    status: z.enum(["pending", "confirmed", "completed", "cancelled"]).optional().describe("Filtra pelo status da aula."),
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de registros retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    let query = supabase.from("bookings").select("id, date, time_slot, status, total_price, notes, student_id, instructor_id, car_id, created_at").or(`student_id.eq.${userId},instructor_id.eq.${userId}`).order("date", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-instructors.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.1.13";
var search_instructors_default = defineTool3({
  name: "search_instructors",
  title: "Buscar instrutores",
  description: "Busca instrutores aprovados na plataforma, com pre\xE7o por hora, avalia\xE7\xE3o, cidade e experi\xEAncia. Aceita filtro por cidade e pre\xE7o m\xE1ximo.",
  inputSchema: {
    city: z2.string().trim().optional().describe("Filtra por cidade (correspond\xEAncia parcial, sem diferenciar mai\xFAsculas)."),
    maxPricePerHour: z2.number().positive().optional().describe("Pre\xE7o m\xE1ximo por hora em reais."),
    limit: z2.number().int().min(1).max(50).default(20).describe("M\xE1ximo de instrutores retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, maxPricePerHour, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_all_approved_instructors");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let list = data ?? [];
    if (city) {
      const needle = city.toLowerCase();
      list = list.filter((i) => String(i.city ?? "").toLowerCase().includes(needle));
    }
    if (maxPricePerHour != null) {
      list = list.filter((i) => Number(i.price_per_hour ?? Infinity) <= maxPricePerHour);
    }
    list = list.slice(0, limit ?? 20);
    return {
      content: [{ type: "text", text: JSON.stringify(list, null, 2) }],
      structuredContent: { instructors: list }
    };
  }
});

// src/lib/mcp/tools/list-my-transactions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.1.13";
var list_my_transactions_default = defineTool4({
  name: "list_my_transactions",
  title: "Meu extrato financeiro",
  description: "Lista as transa\xE7\xF5es financeiras do usu\xE1rio autenticado (cr\xE9ditos, d\xE9bitos, saques) com valor, tipo e status.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("M\xE1ximo de transa\xE7\xF5es retornadas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("transactions").select("id, amount, type, status, description, reference_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-cars.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_cars_default = defineTool5({
  name: "list_my_cars",
  title: "Minha frota",
  description: "Lista os ve\xEDculos cadastrados pelo usu\xE1rio autenticado (investidor), com placa, modelo, status e disponibilidade.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cars").select("id, model, plate, transmission, available, price_per_hour, location_hub, verification_status, created_at").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { cars: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-car-maintenance.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.1.13";
var list_car_maintenance_default = defineTool6({
  name: "list_car_maintenance",
  title: "Hist\xF3rico de manuten\xE7\xE3o",
  description: "Lista os registros de manuten\xE7\xE3o dos ve\xEDculos do usu\xE1rio autenticado (tipo de servi\xE7o, custo, km e pr\xF3xima revis\xE3o).",
  inputSchema: {
    carId: z4.string().uuid().optional().describe("Filtra por um ve\xEDculo espec\xEDfico."),
    limit: z4.number().int().min(1).max(100).default(30).describe("M\xE1ximo de registros retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ carId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("car_maintenance").select("id, car_id, type, description, cost, km, date, next_date, next_km, created_at").eq("owner_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 30);
    if (carId) query = query.eq("car_id", carId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { maintenance: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-car-maintenance.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.1.13";
var add_car_maintenance_default = defineTool7({
  name: "add_car_maintenance",
  title: "Registrar manuten\xE7\xE3o",
  description: "Registra uma manuten\xE7\xE3o de um ve\xEDculo do usu\xE1rio autenticado (ex.: troca de \xF3leo, pneus, motor), com custo, km e pr\xF3xima revis\xE3o.",
  inputSchema: {
    carId: z5.string().uuid().describe("ID do ve\xEDculo (use list_my_cars)."),
    type: z5.string().trim().min(1).describe("Tipo de servi\xE7o, ex.: 'Troca de \xF3leo'."),
    cost: z5.number().min(0).default(0).describe("Custo do servi\xE7o em reais."),
    date: z5.string().optional().describe("Data do servi\xE7o no formato YYYY-MM-DD. Padr\xE3o: hoje."),
    km: z5.number().int().min(0).optional().describe("Quilometragem atual do ve\xEDculo."),
    description: z5.string().trim().optional().describe("Observa\xE7\xF5es do servi\xE7o."),
    nextDate: z5.string().optional().describe("Data da pr\xF3xima revis\xE3o (YYYY-MM-DD)."),
    nextKm: z5.number().int().min(0).optional().describe("Quilometragem da pr\xF3xima revis\xE3o.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ carId, type, cost, date, km, description, nextDate, nextKm }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("car_maintenance").insert({
      owner_id: ctx.getUserId(),
      car_id: carId,
      type,
      cost: cost ?? 0,
      date: date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      km: km ?? null,
      description: description ?? null,
      next_date: nextDate ?? null,
      next_km: nextKm ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Manuten\xE7\xE3o registrada: ${JSON.stringify(data)}` }],
      structuredContent: { maintenance: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yecacgdfdlytkxcwfqpx";
var mcp_default = defineMcp({
  name: "dominebrasil",
  title: "DomineBrasil",
  version: "0.1.0",
  instructions: "Ferramentas da DomineBrasil, marketplace de aulas pr\xE1ticas de dire\xE7\xE3o. Todas as ferramentas atuam em nome do usu\xE1rio autenticado: consulte perfil, aulas agendadas, extrato financeiro, frota de ve\xEDculos e manuten\xE7\xF5es, e busque instrutores aprovados.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_my_bookings_default,
    search_instructors_default,
    list_my_transactions_default,
    list_my_cars_default,
    list_car_maintenance_default,
    add_car_maintenance_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
